Update dwall

diff --git a/Config/preWM/usr_bin/dwall b/Config/preWM/usr_bin/dwall
--- a/Config/preWM/usr_bin/dwall
+++ b/Config/preWM/usr_bin/dwall
@@ -39,6 +39,16 @@ reset_color() {
     return
 }
 
+exit_0(){
+	reset_color
+	exit 0
+}
+
+exit_1(){
+	reset_color
+	exit 1
+}
+
 ## Script Termination
 exit_on_signal_SIGINT() {
     { printf "${RED}\n\n%s\n\n" "[!] Program Interrupted." 2>&1; reset_color; }
@@ -184,7 +194,7 @@ get_img() {
 		FORMAT="jpg"
 	else
 		echo -e ${RED}"[!] Invalid image file, Exiting..."
-		{ reset_color; exit 1; }
+		exit_1
 	fi
 }
 
@@ -208,7 +218,7 @@ pywal_set() {
 	get_img "$1"
 	if ! pywal_backend "$2"; then
 		echo -e ${RED}"[!] $2 is not a valid pywal backend. Check valid backends with `wal --backend`. Exiting..."
-		{ reset_color; exit 1; }
+		exit_1
 	fi
 	if [[ -x `command -v wal` ]]; then
 		local walcmd=(wal --backend "$2" -i "$image.$FORMAT" -n)
@@ -219,7 +229,7 @@ pywal_set() {
 		set_wallpaper "$1"				
 	else
 		echo -e ${RED}"[!] pywal is not installed on your system, exiting..."
-		{ reset_color; exit 1; }
+		exit_1
 	fi
 }
 
@@ -266,8 +276,7 @@ check_style() {
 		reset_color
 	else
 		echo -e ${RED}"[!] Invalid style name : ${GREEN}$1${RED}, exiting..."
-		reset_color
-		exit 1
+		exit_1
 	fi
 }
 
@@ -391,8 +400,31 @@ Download_wallpapers_now(){
 	yn=${yn^^}
 	case $yn in 
 		YES|Y) 
-			echo "Downloading 1-2 urls for wallpapers"
-			git clone https://github.com/adi1090x/dynamic-wallpaper			/tmp/dynamic-wallpaper  2>/dev/null
+			echo "Downloading 1-3 urls for wallpapers"
+			git clone https://github.com/adi1090x/dynamic-wallpaper			/tmp/dynamic-wallpaper
+			mv /tmp/dynamic-wallpaper/images/* /tmp/dynamic_wallpapers 2>/dev/null
+		;;
+		NO|N) echo "skipping Download...";
+		;;
+		* ) >&2 printf '\033[31;1merror :\033[m %s\n' invalid response;
+			Do_want_to_install_not_installed_apps_are;;
+	esac
+	
+	echo "Download wallpapers for https://github.com/adi1090x/dynamic-wallpaper"
+	echo "size wallpaper is 150 MB"
+	read -p "Do you want to proceed? (yes/no) " yn
+	yn=${yn^^}
+	case $yn in 
+		YES|Y) 
+			echo "Downloading 2-3 urls for wallpapers"
+			mkdir -p /tmp/dynamic-wallpaper/images/
+			mkdir -p /tmp/dynamic-wallpaper/tempfornow
+			wget -P /tmp/dynamic-wallpaper/tempfornow https://raw.githubusercontent.com/adi1090x/files/master/dynamic-wallpaper/wallpapers/{catalina,london,maldives,mojaveHD,mountfuji,seoul}.tar.gz
+			mkdir -p /tmp/dynamic-wallpaper/images/london
+			tar -xvf "/tmp/dynamic-wallpaper/tempfornow/london.tar.gz" -C /tmp/dynamic-wallpaper/images/london && mv "/tmp/dynamic-wallpaper/tempfornow/london.tar.gz" /tmp/dynamic-wallpaper
+			mkdir -p /tmp/dynamic-wallpaper/images/mountfuji
+			tar -xvf "/tmp/dynamic-wallpaper/tempfornow/mountfuji" -C /tmp/dynamic-wallpaper/images/mountfuji && mv "/tmp/dynamic-wallpaper/tempfornow/mountfuji.tar.gz" /tmp/dynamic-wallpaper
+			for f in /tmp/dynamic-wallpaper/tempfornow/*.tar.gz -C ; do tar -xvf "$f" -C "/tmp/dynamic-wallpaper/images/"; done
 			mv /tmp/dynamic-wallpaper/images/* /tmp/dynamic_wallpapers 2>/dev/null
 		;;
 		NO|N) echo "skipping Download...";
@@ -407,10 +439,13 @@ Download_wallpapers_now(){
 	yn=${yn^^}
 	case $yn in 
 		YES|Y) 
-			echo "Downloading 2-2 urls for wallpapers"
-			git clone https://github.com/saint-13/Linux_Dynamic_Wallpapers	/tmp/Linux_Dynamic_Wallpapers 2>/dev/null
+			echo "Downloading 3-3 urls for wallpapers"
+			git clone https://github.com/saint-13/Linux_Dynamic_Wallpapers	/tmp/Linux_Dynamic_Wallpapers
 			cd /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers
 			/bin/rm -f * 2>/dev/null
+			
+			rm -rdf /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers/Mojave
+			
 			cd /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers/cyberpunk-01
 			extension="jpg"
 			mv *-10.${extension} cyberpunk-00-0-0.0.${extension}
@@ -441,35 +476,7 @@ Download_wallpapers_now(){
 			mv 1.${extension} 3.${extension}
 			Create_links_for_folders_now
 			
-			cd /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers/Mojave
-			extension="jpeg"
-			mv *_15.${extension} cmojave_dynamic_0_0_0.${extension}
-			mv *_14.${extension} mojave_dynamic_0_0_1.${extension}
-			newName=0
-			for filename in *; do
-				mv "$filename" "${newName}.${extension}"
-				let newName=newName+1
-			done
-			mv 15.${extension} 21.${extension}
-			mv 14.${extension} 19.${extension}
-			mv 13.${extension} 18.${extension}
-			mv 12.${extension} 17.${extension}
-			mv 11.${extension} 16.${extension}
-			mv 10.${extension} 15.${extension}
-			mv 9.${extension} 14.${extension}
-			mv 8.${extension} 13.${extension}
-			mv 7.${extension} 12.${extension}
-			mv 6.${extension} 11.${extension}
-			mv 5.${extension} 9.${extension}
-			mv 4.${extension} 7.${extension}
-			mv 3.${extension} 6.${extension}
-			mv 2.${extension} 5.${extension}
-			mv 1.${extension} 3.${extension}
-			Create_links_for_folders_now
-			
-			cd /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers
 			mv /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers/cyberpunk-01 /tmp/dynamic_wallpapers
-			mv /tmp/Linux_Dynamic_Wallpapers/Dynamic_Wallpapers/Mojave /tmp/dynamic_wallpapers
 			
 			extension=""
 			folder_2_convert_2_Dywall=""
@@ -498,16 +505,15 @@ Download_wallpapers_now(){
 	esac
 	
 	if [ ! -d /tmp/Linux_Dynamic_Wallpapers ] && [ ! -d /tmp/dynamic-wallpaper ]; then
-		exit 0
+		exit_0
 	fi
 	
 	sudo mkdir -p $DIR
 	echo $DIR
 	sudo cp -r /tmp/dynamic_wallpapers/* $DIR
 	echo $DIR
-	reset_color
 	echo "Done"
-	exit 0
+	exit_1
 }
 
 ## Uninstall script
