Update update-notification

diff --git a/Config/openbox/user_bin/update-notification b/Config/openbox/user_bin/update-notification
--- a/Config/openbox/user_bin/update-notification
+++ b/Config/openbox/user_bin/update-notification
@@ -16,7 +16,54 @@
 updates_file="/var/cache/update-notification"
 install_file="/usr/bin/$(basename $0)" 
 cron_when="daily"								# weekly | monthly | daily | hourly
+NOTIFY_ICON=/usr/share/icons/Papirus/32x32/apps/system-software-update.svg
 
+get_total_updates() { UPDATES=$(cat "$updates_file" | wc -l); }
+
+
+#=== FUNCTIONs ==================================================================
+# NAME: Massage system
+# all Bold
+#===============================================================================
+
+plain() {
+	#no color
+	(( QUIET )) && return
+	local mesg=$1; shift
+	printf "\e[1;1m    ${mesg}\e[1;0m\n" "$@" >&1
+}
+
+msg() {
+	# green
+	(( QUIET )) && return
+	local mesg=$1; shift
+	printf "\e[1;1m\e[1;32m==>\e[1;0m\e[1;1m ${mesg}\e[1;0m\n" "$@" >&1
+}
+
+msg2() {
+	# blue
+	(( QUIET )) && return
+	local mesg=$1; shift
+	printf "\e[1;1m\e[1;34m  ->\e[1;0m\e[1;1m ${mesg}\e[1;0m\n" "$@" >&1
+}
+
+ask() {
+	# blue
+	local mesg=$1; shift
+	printf "\e[1;1m\e[1;34m::\e[1;0m\e[1;1m ${mesg}\e[1;0m" "$@" >&1
+}
+
+warning() {
+	# yellow
+	local mesg=$1; shift
+	printf "\e[1;1m\e[1;33m==> $(gettext "WARNING:")\e[1;0m\e[1;1m ${mesg}\e[1;0m\n" "$@" >&2
+}
+
+error() {
+	# red
+	local mesg=$1; shift
+	printf "\e[1;1m\e[1;31m==> $(gettext "ERROR:")\e[1;0m\e[1;1m ${mesg}\e[1;0m\n" "$@" >&2
+}
 
 
 #=== FUNCTION ==================================================================
@@ -27,16 +74,16 @@ function update () {
 	# If no update today exec update
 	if ! [ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ]; then
 		# CHECK INTERNET CONNECTION
-		echo "Checking Internet connection..."
+		plain "Checking Internet connection..."
 		ping -c 1 8.8.8.8 &>/dev/null || exit 1
 
 		# REPOSITORY UPDATE-NOTIFICATION
-		echo "Updating package repositoriy..."
+		plain "Updating package repositoriy..."
 		apt-get update &> /dev/null
 	fi
 	
-	echo "Checking updates and saving in $updates_file..."
-	echo -n "" > "$updates_file" 
+	plain "Checking updates and saving in $updates_file..."
+	printf "" > "$updates_file" 
 	for i in $(apt list --upgradable -a  2>/dev/null | awk -F/ '{print $1}' | grep -v Listing... | uniq)
 	do 
 		dpkg -l | grep -e "$i" >> $updates_file
@@ -44,10 +91,10 @@ function update () {
 
 	# No updates
 	if [ ! -s "$updates_file" ]; then
-		echo -e "\e[1mNO PENDING UPDATES\e[0m"
+		msg "NO PENDING UPDATES"
 	# Pending updates
 	else
-		echo -e "\e[1mPENDING UPDATES\e[0m"
+		warning "PENDING UPDATES"
 		cat "$updates_file"
 	fi
 }
@@ -62,6 +109,7 @@ function interactive_upgrade() {
 	echo
 	[ ! -s "$updates_file" ] && exit 0
 
+	warning "You are about to upgrade your system."
 	read -p "Press enter to continue upgrade..."
 	echo
 	
@@ -73,20 +121,33 @@ function interactive_upgrade() {
 
 	echo -n "" > "$updates_file"
 	
-	# Restart tint2 session
-	pgrep tint2 &>/dev/null && which tint2-session &>/dev/null && tint2-session &>/dev/null
-
 	echo
 	read -p "Update complete!"
 	exit
 }
 
 #=== FUNCTION ==================================================================
-# NAME: tint2_executor_msg
+# NAME: notifcation system
 # DESCRIPTION: shot text for display in systray
 #===============================================================================
 function tint2_executor_msg {
-	[ -s "$updates_file" ] && echo $(wc "$updates_file" -l | cut -f 1 -d " ")" UPDATES  //"
+	if [ -s "$updates_file" ]
+	then
+	    get_total_updates
+	    # notify user of updates
+	    if hash notify-send &>/dev/null; then
+		if (( UPDATES > 50 )); then
+		    notify-send -u critical -i $NOTIFY_ICON \
+			"You really need to update!!" "$UPDATES New packages"
+		elif (( UPDATES > 25 )); then
+		    notify-send -u normal -i $NOTIFY_ICON \
+			"You should update soon" "$UPDATES New packages"
+		elif (( UPDATES > 2 )); then
+		    notify-send -u low -i $NOTIFY_ICON \
+			"$UPDATES New packages"
+		fi
+	    fi		
+	fi
 	exit 0
 }
 
@@ -106,20 +167,6 @@ function install {
 	rm "/etc/cron.$cron_when/$(basename $install_file)" &> /dev/null
 	ln -s "$install_file" "/etc/cron.$cron_when"  || exit 1
 	
-	echo '
-Manual config needed for tint2:
-execp = new
-execp_command = '"$(basename $install_file)"' -m
-execp_lclick_command = x-terminal-emulator -b -e '"$(basename $install_file)"' -i
-execp_tooltip = Pending updates...
-execp_interval = 0
-execp_background_id = 4
-execp_font = Droid Sans 10
-execp_font_color = #FFFFFF 100
-execp_centered = 1
-execp_padding = 8 0 0
-'
-
 	touch "$updates_file"
 	chmod a+w "$updates_file"
 
@@ -148,7 +195,7 @@ function uninstall {
 # DESCRIPTION: Show command help
 #===============================================================================
 function help() {
-	echo -e 'Checks apt updates and show it to user in tint2 taskbar
+	echo -e 'Checks apt updates and show it to user in dunst taskbar
 Usage: '$(basename $0)' -[huc]
    \e[1m-h\e[0m\tShow command help
    \e[1m-i\e[0m\tStart interactive upgrade
